src = $(wildcard src/*.c) $(wildcard src/unix/*.c)
obj = $(src:.c=.o)
dep = $(src:.c=.d)
bin = game

#opt = -O3
dbg = -g
warn = -pedantic -Wall

CFLAGS = $(warn) $(opt) $(dbg) -Isrc -Isrc/unix -MMD
LDFLAGS = -lX11 -lm

$(bin): $(obj)
	$(CC) -o $@ $(obj) $(LDFLAGS)

-include $(dep)

.PHONY: clean
clean:
	rm -f $(obj)
	rm -f $(bin)

.PHONY: cleandep
cleandep:
	rm -f $(dep)
