name: GNU/Linux build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: install dependencies
      run: sudo apt-get install libsdl1.2-dev subversion libpng-dev libjpeg-dev fonts-ubuntu

    - name: get assets
      run: svn co svn://nuclear.mutantstargoat.com/datadirs/winjam24 data

    - name: configure
      run: ./configure --enable-opt

    - name: build assets
      run: |
        mv data/src datasrc
        make data

    - name: build game
      run: make

    - uses: actions/upload-artifact@v4
      with:
        name: game-gnulinux
        path: |
          data/
          sdlgame

# vi:ts=2 sts=2 sw=2 expandtab:
